// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/cloudogu/k8s-exposition-lib/api/v1"
	apiv1 "github.com/cloudogu/k8s-exposition-lib/client/typed/api/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeExpositions implements ExpositionInterface
type fakeExpositions struct {
	*gentype.FakeClientWithList[*v1.Exposition, *v1.ExpositionList]
	Fake *FakeApiV1
}

func newFakeExpositions(fake *FakeApiV1, namespace string) apiv1.ExpositionInterface {
	return &fakeExpositions{
		gentype.NewFakeClientWithList[*v1.Exposition, *v1.ExpositionList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("expositions"),
			v1.SchemeGroupVersion.WithKind("Exposition"),
			func() *v1.Exposition { return &v1.Exposition{} },
			func() *v1.ExpositionList { return &v1.ExpositionList{} },
			func(dst, src *v1.ExpositionList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ExpositionList) []*v1.Exposition { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ExpositionList, items []*v1.Exposition) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
