// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	apiv1 "github.com/cloudogu/k8s-exposition-lib/api/v1"
	scheme "github.com/cloudogu/k8s-exposition-lib/client/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ExpositionsGetter has a method to return a ExpositionInterface.
// A group's client should implement this interface.
type ExpositionsGetter interface {
	Expositions(namespace string) ExpositionInterface
}

// ExpositionInterface has methods to work with Exposition resources.
type ExpositionInterface interface {
	Create(ctx context.Context, exposition *apiv1.Exposition, opts metav1.CreateOptions) (*apiv1.Exposition, error)
	Update(ctx context.Context, exposition *apiv1.Exposition, opts metav1.UpdateOptions) (*apiv1.Exposition, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, exposition *apiv1.Exposition, opts metav1.UpdateOptions) (*apiv1.Exposition, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*apiv1.Exposition, error)
	List(ctx context.Context, opts metav1.ListOptions) (*apiv1.ExpositionList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *apiv1.Exposition, err error)
	ExpositionExpansion
}

// expositions implements ExpositionInterface
type expositions struct {
	*gentype.ClientWithList[*apiv1.Exposition, *apiv1.ExpositionList]
}

// newExpositions returns a Expositions
func newExpositions(c *ApiV1Client, namespace string) *expositions {
	return &expositions{
		gentype.NewClientWithList[*apiv1.Exposition, *apiv1.ExpositionList](
			"expositions",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1.Exposition { return &apiv1.Exposition{} },
			func() *apiv1.ExpositionList { return &apiv1.ExpositionList{} },
		),
	}
}
